export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_RECEIVED = "PRODUCTS_RECEIVED";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_NAME = "FILTER_BY_NAME";
